### ISSUE TITLE
Error after installation, component crashes.

### ISSUE THREAD

**Issue by podeig** [retrofuturejosh/react-modular-audio-player#1]
After installation of the component I get en such error when I run my app:

Error in dos-console:
Unable to resolve some modules:
  "!!../../node_modules/css-loader/index.js!../../node_modules/sass-loader/lib/loader.js!./audioPlayerStyle.scss" in
/Users/john/Development/myapp/node_modules/react-modular-audio-player/build/index.js (web.browser)
                                              
Unable to resolve some modules:
  "!!../../node_modules/css-loader/index.js!../../node_modules/sass-loader/lib/loader.js!./audioPlayerStyle.scss" in
/Users/john/Development/myapp/node_modules/react-modular-audio-player/build/index.js (web.browser.legacy)

Error in browser-console:
Error: Cannot find module 'module'

Do you have any solution for this?

**Comment by retrofuturejosh** [comment]
I'm not able to recreate this problem. Try deleting your node_modules folder and run 'npm install' again. It may be a problem with your package.json or your node_modules folder.
