### ISSUE TITLE
Change behaviour of pause button to restart stream

### ISSUE THREAD

**Issue by benhaldenby** [retrofuturejosh/react-modular-audio-player#13]
I'm using the audio player to play a live mp3 stream from a URL. When the player is paused and re-played, I want to re-fetch the stream and begin playing from the 'live' position. Is this possible? How would I go about adapting the current code to do this? Thanks!

**Comment by retrofuturejosh** [comment]
I'm not sure how a live stream mp3 works. The functionality of playing/pausing is in build/src/functions/playPause. You can probably handle it using the audioRef. Maybe use audioRef.currentTime if you're tracking the current time of the live stream when paused? I'm not sure how live streaming works in this context tho. Feel free to fork and play with the code as needed.
