### ISSUE TITLE
Autoplay

### ISSUE THREAD

**Issue by marisaoliva** [retrofuturejosh/react-modular-audio-player#2]
Hello

Is there any method or prop for the autoplay?

Thanks for the player :D

**Comment by retrofuturejosh** [comment]
Thanks for your interest in the player. 

As someone who hates when any sound autoplays on my browser, I've chosen not to include this feature.

Feel free to fork the repo and add autoplay if you'd like.

Thanks!

**Comment by pablomikel** [comment]
Hi, 
Love this player! One quick question -- I have multiple audio sources on my site and have been able to implement clicking on an audio source to update the audioFiles prop. Is there a way to trigger 'play' during this process so that the new audio source autoplays? Thanks!
