### ISSUE TITLE
Publish as JavaScript module

### ISSUE THREAD

**Issue by v1rtl** [retrofuturejosh/react-modular-audio-player#4]
It would be cool if we could use this component from `mjs`. You can publish the component on [unpkg](https://unpkg) so we will be able to import it like this:

```html
<script type="module">
import AudioPlayer from 'https://unpkg/react-modular-audio-player?module'

render(<AudioPlayer />, document.body)
</script>
```

**Comment by retrofuturejosh** [comment]
If you want to fork the repo and build that, I'm all about it. However, I only intend to support the project as a React Component.

**Comment by v1rtl** [comment]
JS modules work fine with React components.

Here's a [component](https://github.com/souporserious/react-measure) that has ESM module.
