### ISSUE TITLE
css issue

### ISSUE THREAD

**Issue by andykotov** [retrofuturejosh/react-modular-audio-player#9]
![image](https://user-images.githubusercontent.com/52244477/70835222-11c4c780-1e05-11ea-9992-0f803cce7cfa.png)

your css for audio player redefined my own css and changed all my images in the app

**Comment by retrofuturejosh** [comment]
@IHakoda, I can see how that would be frustrating. I updated the css to target a different class. This change is merged in master and part of react-modular-audio-player version 1.2.0

Thanks for helping make it a better package!
